services:
  db:
    image: postgres
    container_name: postgresdb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
  app:
    image: vitorpc4/schoolpost
    container_name: schoolpostbackend
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      - NODE_ENV=production
      - DATABASE_HOST=postgresdb
      - DATABASE_USER=root
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=schoolpost
      - DATABASE_PORT=5432
      - PORT=3001
      - JWT_SECRET=secret
      - JWT_EXPIRES_IN=120m
      - JWT_SECRET_INVITE=supersupersecret
  schoolpostfront:
    image: vitorpc4/schoolpostfront
    container_name: schoolpostfront
    ports:
      - "3020:3020"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_SCHOOL_BACKEND: http://host.docker.internal:3001
    depends_on:
      - db
      - app
