import type { Metadata } from "next";
import "./globals.css";
import { QueryClientCofigProvider } from "./context/QueryClientProvider";
import { SchoolProvider } from "./context/SchoolContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body>
        <SchoolProvider>
          <section>
            <QueryClientCofigProvider>{children}</QueryClientCofigProvider>
          </section>
        </SchoolProvider>
      </body>
    </html>
  );
}
